fix: Error with << overload for GENRE resolved
GENRE was made public and accessible to the << overload for Book because
the getter genre() thru errors,

src/../headers/library.h:15:44: error: unknown type name 'Book'
std::ostream& operator<<(std::ostream& os, Book& book);
                                           ^
src/../headers/library.h:16:44: error: unknown type name 'Genre'
std::ostream& operator<<(std::ostream& os, Genre& genre);
                                           ^
src/../headers/library.h:90:26: error: invalid operands to binary
  expression ('basic_ostream<char, std::char_traits<char>>' and 'Genre')
            << "Genre: " << book.GENRE << '\n'
            ~~~~~~~~~~~~ ^  ~~~~~~~~~~

These were resolved by adding const before Genre& genre in the args for
the GENRE << overload. I'm not sure why this works yet.